/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;

/**
 *
 * @author Revij
 */
public class InterfazHospital extends javax.swing.JFrame {

    /**
     * Creates new form InterfazHospital
     */
    private javax.swing.JTextField[] puestosCuadroTexto = new javax.swing.JTextField[10]; 
    
    public InterfazHospital() {
        initComponents();
        puestosCuadroTexto[0] = puestoVacunacion1;
        puestosCuadroTexto[1] = puestoVacunacion2;
        puestosCuadroTexto[2] = puestoVacunacion3;
        puestosCuadroTexto[3] = puestoVacunacion4;
        puestosCuadroTexto[4] = puestoVacunacion5;
        puestosCuadroTexto[5] = puestoVacunacion6;
        puestosCuadroTexto[6] = puestoVacunacion7;
        puestosCuadroTexto[7] = puestoVacunacion8;
        puestosCuadroTexto[8] = puestoVacunacion9;
        puestosCuadroTexto[9] = puestoVacunacion10;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recepcionPanel = new javax.swing.JPanel();
        recepcionLabel = new javax.swing.JLabel();
        pacienteAtendido = new javax.swing.JTextField();
        auxiliarTrabajando = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        colaPacientes = new javax.swing.JTextArea();
        pacienteRecepcionLabel = new javax.swing.JLabel();
        auxiliarRecepcionLabel = new javax.swing.JLabel();
        colaEsperaRecepcionLabel = new javax.swing.JLabel();
        salaDescansoPanel = new javax.swing.JPanel();
        salaDescansoLabel = new javax.swing.JLabel();
        salaDescansoTextArea = new javax.swing.JScrollPane();
        salaDescanso = new javax.swing.JTextArea();
        salaVacunacionPanel = new javax.swing.JPanel();
        salaVacunacionLabel = new javax.swing.JLabel();
        puestoVacunacion1 = new javax.swing.JTextField();
        puesto1VacunacionLabel = new javax.swing.JLabel();
        puestoVacunacion2 = new javax.swing.JTextField();
        puesto2VacunacionLabel = new javax.swing.JLabel();
        puestoVacunacion3 = new javax.swing.JTextField();
        puesto3VacunacionLabel = new javax.swing.JLabel();
        puestoVacunacion4 = new javax.swing.JTextField();
        puesto4VacunacionLabel = new javax.swing.JLabel();
        puestoVacunacion5 = new javax.swing.JTextField();
        puesto5VacunacionLabel = new javax.swing.JLabel();
        puestoVacunacion6 = new javax.swing.JTextField();
        puesto6VacunacionLabel = new javax.swing.JLabel();
        puestoVacunacion7 = new javax.swing.JTextField();
        puesto7VacunacionLabel = new javax.swing.JLabel();
        puestoVacunacion8 = new javax.swing.JTextField();
        puesto8VacunacionLabel = new javax.swing.JLabel();
        puestoVacunacion9 = new javax.swing.JTextField();
        puesto9VacunacionLabel = new javax.swing.JLabel();
        puestoVacunacion10 = new javax.swing.JTextField();
        puesto10VacunacionLabel = new javax.swing.JLabel();
        auxiliarVacunacionTextField = new javax.swing.JTextField();
        auxiliarVacunacionLabel = new javax.swing.JLabel();
        vacunasDispoVacunacionTextField = new javax.swing.JTextField();
        vacunasDispoVacunacionLabel = new javax.swing.JLabel();
        salaObservacionPanel = new javax.swing.JPanel();
        salaObservacionLabel = new javax.swing.JLabel();
        puestoObservacion1 = new javax.swing.JTextField();
        puesto1ObservacionLabel = new javax.swing.JLabel();
        puestoObservacion2 = new javax.swing.JTextField();
        puesto2ObservacionLabel = new javax.swing.JLabel();
        puestoObservacion3 = new javax.swing.JTextField();
        puesto3ObservacionLabel = new javax.swing.JLabel();
        puestoObservacion4 = new javax.swing.JTextField();
        puesto4ObservacionLabel = new javax.swing.JLabel();
        puestoObservacion5 = new javax.swing.JTextField();
        puesto5ObservacionLabel = new javax.swing.JLabel();
        puestoObservacion6 = new javax.swing.JTextField();
        puesto6ObservacionLabel = new javax.swing.JLabel();
        puestoObservacion7 = new javax.swing.JTextField();
        puesto7ObservacionLabel = new javax.swing.JLabel();
        puestoObservacion8 = new javax.swing.JTextField();
        puesto8ObservacionLabel = new javax.swing.JLabel();
        puestoObservacion9 = new javax.swing.JTextField();
        puesto9ObservacionLabel = new javax.swing.JLabel();
        puestoObservacion10 = new javax.swing.JTextField();
        puesto10ObservacionLabel = new javax.swing.JLabel();
        puestoObservacion11 = new javax.swing.JTextField();
        puesto11ObservacionLabel = new javax.swing.JLabel();
        puestoObservacion12 = new javax.swing.JTextField();
        puesto12ObservacionLabel = new javax.swing.JLabel();
        puestoObservacion13 = new javax.swing.JTextField();
        puesto13ObservacionLabel = new javax.swing.JLabel();
        puestoObservacion14 = new javax.swing.JTextField();
        puesto14ObservacionLabel = new javax.swing.JLabel();
        puestoObservacion15 = new javax.swing.JTextField();
        puesto15ObservacionLabel = new javax.swing.JLabel();
        puestoObservacion16 = new javax.swing.JTextField();
        puesto16ObservacionLabel = new javax.swing.JLabel();
        puestoObservacion17 = new javax.swing.JTextField();
        puesto17ObservacionLabel = new javax.swing.JLabel();
        puestoObservacion18 = new javax.swing.JTextField();
        puesto18ObservacionLabel = new javax.swing.JLabel();
        puestoObservacion19 = new javax.swing.JTextField();
        puesto19ObservacionLabel = new javax.swing.JLabel();
        puestoObservacion20 = new javax.swing.JTextField();
        puesto20ObservacionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        recepcionPanel.setBackground(new java.awt.Color(153, 153, 153));
        recepcionPanel.setForeground(new java.awt.Color(0, 255, 204));

        recepcionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        recepcionLabel.setText("RECEPCIÓN");

        pacienteAtendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacienteAtendidoActionPerformed(evt);
            }
        });

        auxiliarTrabajando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auxiliarTrabajandoActionPerformed(evt);
            }
        });

        colaPacientes.setColumns(20);
        colaPacientes.setRows(5);
        jScrollPane1.setViewportView(colaPacientes);

        pacienteRecepcionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        pacienteRecepcionLabel.setText("Paciente");

        auxiliarRecepcionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        auxiliarRecepcionLabel.setText("Auxiliar");

        colaEsperaRecepcionLabel.setText("Cola de espera");

        javax.swing.GroupLayout recepcionPanelLayout = new javax.swing.GroupLayout(recepcionPanel);
        recepcionPanel.setLayout(recepcionPanelLayout);
        recepcionPanelLayout.setHorizontalGroup(
            recepcionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recepcionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(recepcionLabel)
                .addGap(315, 315, 315))
            .addGroup(recepcionPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(recepcionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(recepcionPanelLayout.createSequentialGroup()
                        .addGroup(recepcionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pacienteRecepcionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pacienteAtendido))
                        .addGap(83, 83, 83)
                        .addGroup(recepcionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(auxiliarRecepcionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(auxiliarTrabajando)))
                    .addComponent(colaEsperaRecepcionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        recepcionPanelLayout.setVerticalGroup(
            recepcionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recepcionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(recepcionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(colaEsperaRecepcionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(recepcionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pacienteRecepcionLabel)
                    .addComponent(auxiliarRecepcionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(recepcionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(auxiliarTrabajando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pacienteAtendido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        salaDescansoPanel.setBackground(new java.awt.Color(153, 153, 153));

        salaDescansoLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        salaDescansoLabel.setText("SALA DE DESCANSO");

        salaDescanso.setColumns(20);
        salaDescanso.setRows(5);
        salaDescansoTextArea.setViewportView(salaDescanso);

        javax.swing.GroupLayout salaDescansoPanelLayout = new javax.swing.GroupLayout(salaDescansoPanel);
        salaDescansoPanel.setLayout(salaDescansoPanelLayout);
        salaDescansoPanelLayout.setHorizontalGroup(
            salaDescansoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salaDescansoPanelLayout.createSequentialGroup()
                .addGroup(salaDescansoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(salaDescansoPanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(salaDescansoTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(salaDescansoPanelLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(salaDescansoLabel)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        salaDescansoPanelLayout.setVerticalGroup(
            salaDescansoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salaDescansoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(salaDescansoLabel)
                .addGap(31, 31, 31)
                .addComponent(salaDescansoTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        salaVacunacionPanel.setBackground(new java.awt.Color(153, 153, 153));

        salaVacunacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        salaVacunacionLabel.setText("SALA DE VACUNACIÓN");

        puestoVacunacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puestoVacunacion1ActionPerformed(evt);
            }
        });

        puesto1VacunacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        puesto1VacunacionLabel.setText("Puesto 1");

        puestoVacunacion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puestoVacunacion2ActionPerformed(evt);
            }
        });

        puesto2VacunacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        puesto2VacunacionLabel.setText("Puesto 2");

        puestoVacunacion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puestoVacunacion3ActionPerformed(evt);
            }
        });

        puesto3VacunacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        puesto3VacunacionLabel.setText("Puesto 3");

        puestoVacunacion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puestoVacunacion4ActionPerformed(evt);
            }
        });

        puesto4VacunacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        puesto4VacunacionLabel.setText("Puesto 4");

        puestoVacunacion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puestoVacunacion5ActionPerformed(evt);
            }
        });

        puesto5VacunacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        puesto5VacunacionLabel.setText("Puesto 5");

        puesto6VacunacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        puesto6VacunacionLabel.setText("Puesto 6");

        puesto7VacunacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        puesto7VacunacionLabel.setText("Puesto 7");

        puesto8VacunacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        puesto8VacunacionLabel.setText("Puesto 8");

        puesto9VacunacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        puesto9VacunacionLabel.setText("Puesto 9");

        puesto10VacunacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        puesto10VacunacionLabel.setText("Puesto 10");

        auxiliarVacunacionTextField.setText("jTextField4");
        auxiliarVacunacionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auxiliarVacunacionTextFieldActionPerformed(evt);
            }
        });

        auxiliarVacunacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        auxiliarVacunacionLabel.setText("Auxiliar");

        vacunasDispoVacunacionTextField.setText("jTextField10");

        vacunasDispoVacunacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        vacunasDispoVacunacionLabel.setText("Vacunas Disponibles");

        javax.swing.GroupLayout salaVacunacionPanelLayout = new javax.swing.GroupLayout(salaVacunacionPanel);
        salaVacunacionPanel.setLayout(salaVacunacionPanelLayout);
        salaVacunacionPanelLayout.setHorizontalGroup(
            salaVacunacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salaVacunacionPanelLayout.createSequentialGroup()
                .addGap(483, 483, 483)
                .addComponent(salaVacunacionLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(salaVacunacionPanelLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(salaVacunacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(puestoVacunacion6, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(puestoVacunacion1)
                    .addComponent(puesto1VacunacionLabel)
                    .addComponent(puesto6VacunacionLabel))
                .addGap(18, 18, 18)
                .addGroup(salaVacunacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(salaVacunacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(puestoVacunacion2, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addComponent(puestoVacunacion7))
                    .addComponent(puesto2VacunacionLabel)
                    .addComponent(puesto7VacunacionLabel))
                .addGap(18, 18, 18)
                .addGroup(salaVacunacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(salaVacunacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(puestoVacunacion3, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addComponent(puestoVacunacion8))
                    .addComponent(puesto3VacunacionLabel)
                    .addComponent(puesto8VacunacionLabel))
                .addGap(18, 18, 18)
                .addGroup(salaVacunacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(salaVacunacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(puestoVacunacion4, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addComponent(puestoVacunacion9))
                    .addComponent(puesto4VacunacionLabel)
                    .addComponent(puesto9VacunacionLabel))
                .addGap(18, 18, 18)
                .addGroup(salaVacunacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(salaVacunacionPanelLayout.createSequentialGroup()
                        .addGroup(salaVacunacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(puestoVacunacion5, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(puestoVacunacion10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(salaVacunacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(auxiliarVacunacionTextField)
                            .addComponent(vacunasDispoVacunacionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(256, 256, 256))
                    .addGroup(salaVacunacionPanelLayout.createSequentialGroup()
                        .addComponent(puesto5VacunacionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(auxiliarVacunacionLabel)
                        .addGap(289, 289, 289))
                    .addGroup(salaVacunacionPanelLayout.createSequentialGroup()
                        .addComponent(puesto10VacunacionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vacunasDispoVacunacionLabel)
                        .addGap(211, 211, 211))))
        );
        salaVacunacionPanelLayout.setVerticalGroup(
            salaVacunacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salaVacunacionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(salaVacunacionLabel)
                .addGap(38, 38, 38)
                .addGroup(salaVacunacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(puesto1VacunacionLabel)
                    .addComponent(puesto2VacunacionLabel)
                    .addComponent(puesto3VacunacionLabel)
                    .addComponent(puesto4VacunacionLabel)
                    .addComponent(puesto5VacunacionLabel)
                    .addComponent(auxiliarVacunacionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(salaVacunacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(puestoVacunacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puestoVacunacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puestoVacunacion3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puestoVacunacion5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auxiliarVacunacionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puestoVacunacion4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(salaVacunacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(puesto6VacunacionLabel)
                    .addComponent(puesto7VacunacionLabel)
                    .addComponent(puesto8VacunacionLabel)
                    .addComponent(puesto9VacunacionLabel)
                    .addComponent(puesto10VacunacionLabel)
                    .addComponent(vacunasDispoVacunacionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(salaVacunacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(puestoVacunacion7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puestoVacunacion6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puestoVacunacion8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puestoVacunacion9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puestoVacunacion10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vacunasDispoVacunacionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        salaObservacionPanel.setBackground(new java.awt.Color(153, 153, 153));

        salaObservacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        salaObservacionLabel.setText("SALA DE OBSERVACIÓN");

        puestoObservacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puestoObservacion1ActionPerformed(evt);
            }
        });

        puesto1ObservacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        puesto1ObservacionLabel.setText("Puesto 1");

        puestoObservacion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puestoObservacion2ActionPerformed(evt);
            }
        });

        puesto2ObservacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        puesto2ObservacionLabel.setText("Puesto 2");

        puestoObservacion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puestoObservacion3ActionPerformed(evt);
            }
        });

        puesto3ObservacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        puesto3ObservacionLabel.setText("Puesto 3");

        puestoObservacion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puestoObservacion4ActionPerformed(evt);
            }
        });

        puesto4ObservacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        puesto4ObservacionLabel.setText("Puesto 4");

        puestoObservacion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puestoObservacion5ActionPerformed(evt);
            }
        });

        puesto5ObservacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        puesto5ObservacionLabel.setText("Puesto 5");

        puestoObservacion6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puestoObservacion6ActionPerformed(evt);
            }
        });

        puesto6ObservacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        puesto6ObservacionLabel.setText("Puesto 6");

        puestoObservacion7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puestoObservacion7ActionPerformed(evt);
            }
        });

        puesto7ObservacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        puesto7ObservacionLabel.setText("Puesto 7 ");

        puestoObservacion8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puestoObservacion8ActionPerformed(evt);
            }
        });

        puesto8ObservacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        puesto8ObservacionLabel.setText("Puesto 8");

        puestoObservacion9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puestoObservacion9ActionPerformed(evt);
            }
        });

        puesto9ObservacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        puesto9ObservacionLabel.setText("Puesto 9");

        puestoObservacion10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puestoObservacion10ActionPerformed(evt);
            }
        });

        puesto10ObservacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        puesto10ObservacionLabel.setText("Puesto 10 ");

        puestoObservacion11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puestoObservacion11ActionPerformed(evt);
            }
        });

        puesto11ObservacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        puesto11ObservacionLabel.setText("Puesto 11");

        puestoObservacion12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puestoObservacion12ActionPerformed(evt);
            }
        });

        puesto12ObservacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        puesto12ObservacionLabel.setText("Puesto 12");

        puestoObservacion13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puestoObservacion13ActionPerformed(evt);
            }
        });

        puesto13ObservacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        puesto13ObservacionLabel.setText("Puesto 13");

        puestoObservacion14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puestoObservacion14ActionPerformed(evt);
            }
        });

        puesto14ObservacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        puesto14ObservacionLabel.setText("Puesto 14");

        puestoObservacion15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puestoObservacion15ActionPerformed(evt);
            }
        });

        puesto15ObservacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        puesto15ObservacionLabel.setText("Puesto 15");

        puestoObservacion16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puestoObservacion16ActionPerformed(evt);
            }
        });

        puesto16ObservacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        puesto16ObservacionLabel.setText("Puesto 16");

        puestoObservacion17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puestoObservacion17ActionPerformed(evt);
            }
        });

        puesto17ObservacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        puesto17ObservacionLabel.setText("Puesto 17 ");

        puestoObservacion18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puestoObservacion18ActionPerformed(evt);
            }
        });

        puesto18ObservacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        puesto18ObservacionLabel.setText("Puesto 18");

        puestoObservacion19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puestoObservacion19ActionPerformed(evt);
            }
        });

        puesto19ObservacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        puesto19ObservacionLabel.setText("Puesto 19");

        puestoObservacion20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puestoObservacion20ActionPerformed(evt);
            }
        });

        puesto20ObservacionLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        puesto20ObservacionLabel.setText("Puesto 20 ");

        javax.swing.GroupLayout salaObservacionPanelLayout = new javax.swing.GroupLayout(salaObservacionPanel);
        salaObservacionPanel.setLayout(salaObservacionPanelLayout);
        salaObservacionPanelLayout.setHorizontalGroup(
            salaObservacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, salaObservacionPanelLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(salaObservacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(salaObservacionPanelLayout.createSequentialGroup()
                        .addComponent(puesto1ObservacionLabel)
                        .addGap(176, 176, 176)
                        .addComponent(puesto3ObservacionLabel))
                    .addGroup(salaObservacionPanelLayout.createSequentialGroup()
                        .addComponent(puestoObservacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(salaObservacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(salaObservacionPanelLayout.createSequentialGroup()
                                .addComponent(puestoObservacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(puestoObservacion3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(puesto2ObservacionLabel))
                        .addGap(18, 18, 18)
                        .addGroup(salaObservacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(puestoObservacion4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(puesto4ObservacionLabel))
                        .addGap(18, 18, 18)
                        .addGroup(salaObservacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(salaObservacionPanelLayout.createSequentialGroup()
                                .addGroup(salaObservacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(puestoObservacion5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(puesto5ObservacionLabel))
                                .addGap(18, 18, 18)
                                .addGroup(salaObservacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(puestoObservacion6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(puesto6ObservacionLabel))
                                .addGap(18, 18, 18)
                                .addGroup(salaObservacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(puestoObservacion7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(puesto7ObservacionLabel))
                                .addGap(18, 18, 18)
                                .addGroup(salaObservacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(puesto8ObservacionLabel)
                                    .addComponent(puestoObservacion8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(salaObservacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(puestoObservacion9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(puesto9ObservacionLabel))
                                .addGap(18, 18, 18)
                                .addGroup(salaObservacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(puesto10ObservacionLabel)
                                    .addComponent(puestoObservacion10, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(salaObservacionLabel)))
                    .addGroup(salaObservacionPanelLayout.createSequentialGroup()
                        .addComponent(puesto11ObservacionLabel)
                        .addGap(176, 176, 176)
                        .addComponent(puesto13ObservacionLabel))
                    .addGroup(salaObservacionPanelLayout.createSequentialGroup()
                        .addComponent(puestoObservacion11, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(salaObservacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(salaObservacionPanelLayout.createSequentialGroup()
                                .addComponent(puestoObservacion12, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(puestoObservacion13, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(puesto12ObservacionLabel))
                        .addGap(18, 18, 18)
                        .addGroup(salaObservacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(puestoObservacion14, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(puesto14ObservacionLabel))
                        .addGap(18, 18, 18)
                        .addGroup(salaObservacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(puestoObservacion15, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(puesto15ObservacionLabel))
                        .addGap(18, 18, 18)
                        .addGroup(salaObservacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(puestoObservacion16, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(puesto16ObservacionLabel))
                        .addGap(18, 18, 18)
                        .addGroup(salaObservacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(puestoObservacion17, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(puesto17ObservacionLabel))
                        .addGap(18, 18, 18)
                        .addGroup(salaObservacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(puesto18ObservacionLabel)
                            .addComponent(puestoObservacion18, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(salaObservacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(puestoObservacion19, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(puesto19ObservacionLabel))
                        .addGap(18, 18, 18)
                        .addGroup(salaObservacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(puesto20ObservacionLabel)
                            .addComponent(puestoObservacion20, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43))
        );
        salaObservacionPanelLayout.setVerticalGroup(
            salaObservacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salaObservacionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(salaObservacionLabel)
                .addGap(47, 47, 47)
                .addGroup(salaObservacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(puesto1ObservacionLabel)
                    .addComponent(puesto2ObservacionLabel)
                    .addComponent(puesto3ObservacionLabel)
                    .addComponent(puesto4ObservacionLabel)
                    .addComponent(puesto5ObservacionLabel)
                    .addComponent(puesto6ObservacionLabel)
                    .addComponent(puesto7ObservacionLabel)
                    .addComponent(puesto9ObservacionLabel)
                    .addComponent(puesto8ObservacionLabel)
                    .addComponent(puesto10ObservacionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(salaObservacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(puestoObservacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puestoObservacion3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puestoObservacion4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puestoObservacion5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puestoObservacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puestoObservacion6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puestoObservacion7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puestoObservacion8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puestoObservacion9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puestoObservacion10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(salaObservacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(puesto11ObservacionLabel)
                    .addComponent(puesto12ObservacionLabel)
                    .addComponent(puesto13ObservacionLabel)
                    .addComponent(puesto14ObservacionLabel)
                    .addComponent(puesto15ObservacionLabel)
                    .addComponent(puesto16ObservacionLabel)
                    .addComponent(puesto17ObservacionLabel)
                    .addComponent(puesto19ObservacionLabel)
                    .addComponent(puesto18ObservacionLabel)
                    .addComponent(puesto20ObservacionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(salaObservacionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(puestoObservacion11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puestoObservacion13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puestoObservacion14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puestoObservacion15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puestoObservacion12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puestoObservacion16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puestoObservacion17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puestoObservacion18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puestoObservacion19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puestoObservacion20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(salaObservacionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salaVacunacionPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(recepcionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(salaDescansoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(salaDescansoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(recepcionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salaVacunacionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salaObservacionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pacienteAtendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacienteAtendidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pacienteAtendidoActionPerformed

    private void auxiliarTrabajandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auxiliarTrabajandoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_auxiliarTrabajandoActionPerformed

    private void puestoVacunacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puestoVacunacion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puestoVacunacion1ActionPerformed

    private void puestoVacunacion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puestoVacunacion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puestoVacunacion2ActionPerformed

    private void puestoVacunacion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puestoVacunacion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puestoVacunacion3ActionPerformed

    private void puestoVacunacion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puestoVacunacion4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puestoVacunacion4ActionPerformed

    private void puestoVacunacion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puestoVacunacion5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puestoVacunacion5ActionPerformed

    private void auxiliarVacunacionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auxiliarVacunacionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_auxiliarVacunacionTextFieldActionPerformed

    private void puestoObservacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puestoObservacion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puestoObservacion1ActionPerformed

    private void puestoObservacion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puestoObservacion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puestoObservacion2ActionPerformed

    private void puestoObservacion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puestoObservacion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puestoObservacion3ActionPerformed

    private void puestoObservacion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puestoObservacion4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puestoObservacion4ActionPerformed

    private void puestoObservacion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puestoObservacion5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puestoObservacion5ActionPerformed

    private void puestoObservacion6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puestoObservacion6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puestoObservacion6ActionPerformed

    private void puestoObservacion7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puestoObservacion7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puestoObservacion7ActionPerformed

    private void puestoObservacion8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puestoObservacion8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puestoObservacion8ActionPerformed

    private void puestoObservacion9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puestoObservacion9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puestoObservacion9ActionPerformed

    private void puestoObservacion10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puestoObservacion10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puestoObservacion10ActionPerformed

    private void puestoObservacion11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puestoObservacion11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puestoObservacion11ActionPerformed

    private void puestoObservacion12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puestoObservacion12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puestoObservacion12ActionPerformed

    private void puestoObservacion13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puestoObservacion13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puestoObservacion13ActionPerformed

    private void puestoObservacion14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puestoObservacion14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puestoObservacion14ActionPerformed

    private void puestoObservacion15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puestoObservacion15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puestoObservacion15ActionPerformed

    private void puestoObservacion16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puestoObservacion16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puestoObservacion16ActionPerformed

    private void puestoObservacion17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puestoObservacion17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puestoObservacion17ActionPerformed

    private void puestoObservacion18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puestoObservacion18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puestoObservacion18ActionPerformed

    private void puestoObservacion19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puestoObservacion19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puestoObservacion19ActionPerformed

    private void puestoObservacion20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puestoObservacion20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puestoObservacion20ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazHospital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel auxiliarRecepcionLabel;
    private javax.swing.JTextField auxiliarTrabajando;
    private javax.swing.JLabel auxiliarVacunacionLabel;
    private javax.swing.JTextField auxiliarVacunacionTextField;
    private javax.swing.JLabel colaEsperaRecepcionLabel;
    private javax.swing.JTextArea colaPacientes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pacienteAtendido;
    private javax.swing.JLabel pacienteRecepcionLabel;
    private javax.swing.JLabel puesto10ObservacionLabel;
    private javax.swing.JLabel puesto10VacunacionLabel;
    private javax.swing.JLabel puesto11ObservacionLabel;
    private javax.swing.JLabel puesto12ObservacionLabel;
    private javax.swing.JLabel puesto13ObservacionLabel;
    private javax.swing.JLabel puesto14ObservacionLabel;
    private javax.swing.JLabel puesto15ObservacionLabel;
    private javax.swing.JLabel puesto16ObservacionLabel;
    private javax.swing.JLabel puesto17ObservacionLabel;
    private javax.swing.JLabel puesto18ObservacionLabel;
    private javax.swing.JLabel puesto19ObservacionLabel;
    private javax.swing.JLabel puesto1ObservacionLabel;
    private javax.swing.JLabel puesto1VacunacionLabel;
    private javax.swing.JLabel puesto20ObservacionLabel;
    private javax.swing.JLabel puesto2ObservacionLabel;
    private javax.swing.JLabel puesto2VacunacionLabel;
    private javax.swing.JLabel puesto3ObservacionLabel;
    private javax.swing.JLabel puesto3VacunacionLabel;
    private javax.swing.JLabel puesto4ObservacionLabel;
    private javax.swing.JLabel puesto4VacunacionLabel;
    private javax.swing.JLabel puesto5ObservacionLabel;
    private javax.swing.JLabel puesto5VacunacionLabel;
    private javax.swing.JLabel puesto6ObservacionLabel;
    private javax.swing.JLabel puesto6VacunacionLabel;
    private javax.swing.JLabel puesto7ObservacionLabel;
    private javax.swing.JLabel puesto7VacunacionLabel;
    private javax.swing.JLabel puesto8ObservacionLabel;
    private javax.swing.JLabel puesto8VacunacionLabel;
    private javax.swing.JLabel puesto9ObservacionLabel;
    private javax.swing.JLabel puesto9VacunacionLabel;
    private javax.swing.JTextField puestoObservacion1;
    private javax.swing.JTextField puestoObservacion10;
    private javax.swing.JTextField puestoObservacion11;
    private javax.swing.JTextField puestoObservacion12;
    private javax.swing.JTextField puestoObservacion13;
    private javax.swing.JTextField puestoObservacion14;
    private javax.swing.JTextField puestoObservacion15;
    private javax.swing.JTextField puestoObservacion16;
    private javax.swing.JTextField puestoObservacion17;
    private javax.swing.JTextField puestoObservacion18;
    private javax.swing.JTextField puestoObservacion19;
    private javax.swing.JTextField puestoObservacion2;
    private javax.swing.JTextField puestoObservacion20;
    private javax.swing.JTextField puestoObservacion3;
    private javax.swing.JTextField puestoObservacion4;
    private javax.swing.JTextField puestoObservacion5;
    private javax.swing.JTextField puestoObservacion6;
    private javax.swing.JTextField puestoObservacion7;
    private javax.swing.JTextField puestoObservacion8;
    private javax.swing.JTextField puestoObservacion9;
    private javax.swing.JTextField puestoVacunacion1;
    private javax.swing.JTextField puestoVacunacion10;
    private javax.swing.JTextField puestoVacunacion2;
    private javax.swing.JTextField puestoVacunacion3;
    private javax.swing.JTextField puestoVacunacion4;
    private javax.swing.JTextField puestoVacunacion5;
    private javax.swing.JTextField puestoVacunacion6;
    private javax.swing.JTextField puestoVacunacion7;
    private javax.swing.JTextField puestoVacunacion8;
    private javax.swing.JTextField puestoVacunacion9;
    private javax.swing.JLabel recepcionLabel;
    private javax.swing.JPanel recepcionPanel;
    private javax.swing.JTextArea salaDescanso;
    private javax.swing.JLabel salaDescansoLabel;
    private javax.swing.JPanel salaDescansoPanel;
    private javax.swing.JScrollPane salaDescansoTextArea;
    private javax.swing.JLabel salaObservacionLabel;
    private javax.swing.JPanel salaObservacionPanel;
    private javax.swing.JLabel salaVacunacionLabel;
    private javax.swing.JPanel salaVacunacionPanel;
    private javax.swing.JLabel vacunasDispoVacunacionLabel;
    private javax.swing.JTextField vacunasDispoVacunacionTextField;
    // End of variables declaration//GEN-END:variables
    
    
    
    public void colaPacientesModificar(String texto){
        colaPacientes.setText(texto);
    }
    
    public void pacienteAtendidoModificar(String texto){
        pacienteAtendido.setText(texto);
    }
    
    public void salaDescansoModificar(String texto){
        salaDescanso.setText(texto);
    }
    
    public void modificarAuxiliar(String texto){
        auxiliarTrabajando.setText(texto);
    }
    
    
    public void pintarVacunacion(String texto, int nmero){
        puestosCuadroTexto[nmero-4].setText(texto);
        
    }
    

}
